[store]
name = "Ikigai Arcade"
info = ""

[game_1]
name = "maimai DX"
info = "Test"
double_queue = true
wait_time = 947
confirm_time = 120

[game_2]
name = "CHUNITHM"
info = ""
double_queue = false
wait_time = 785
confirm_time = 120

[game_3]
name = "ONGEKI"
info = ""
double_queue = false
wait_time = 874
confirm_time = 120

[game_4]
name = "PUMP IT UP"
info = ""
double_queue = true
wait_time = 780
confirm_time = 120
