[store]
name = "Ikigai Arcade"
info = "    1.You are <b>REQUIRED</b> to put yourself in the queue to play any maimai DX credits, with or without a partner. Even if no one else is playing.<p style=\"color:#FF0000;\">‣ <b>You are REQUIRED to use the same name in the queue as your card profile name to confirm your spot.</b></p> If you do not have a profile card put (Guest - Your Name)<br><br>‣ You are NOT allowed to be on the queue multiple times.<br>‣ You are allowed to play before your designated turn if a group did not show up for their turn or someone's partner is not there however, you are REQUIRED to remove your name from the queue before playing. You may only re-queue after your credit has finished. <br>‣ <b>Missing your turn does not give you next play, you may re-add yourself to the end of the queue</b><br>‣ Solo play is not permitted if there are 2 or more groups in the queue.<br>‣ <b>Anyone not using the queue will not be given priority to play next.</b><br>‣ Staff will always give priority to the group in the queue.<br><br><h4>If you are seen attempting to circumvent, bypass or disregard these rules by any means you may be subject to an appropriately deemed penalty according to staff. <br>This includes but is not limited to a credit penalty, your RFPay card being banned and your balance forfeit, removal from the venue or permanently banned.</h4><br><br><i>Issues regarding the queue or can't remove your name?<br>Please see the front desk for assistance.</i><br><br><p style=\"color:#FF0000;\">2. <b>Rhythm Game Gloves are REQUIRED to play maimai DX.<br>‣ No exceptions!</b></p>‣ You will be asked to stop playing and your credit may be forfeit if you are not playing with rhythm game gloves.<br><br><p style=\"color:#FF0000;\">3. <b> NO watches, rings or any wrist/finger jewelry are permitted to be worn while playing maimai DX.</b></p>‣ You will be asked to stop playing and your credit may be forfeit if you are wearing any of the above mentioned items. <br><p style=\"color:#FF0000;\">‣ We will hold players responsible for any damage that occurs.<br></p>4. <b>If the screen is FLASHING WHITE frequently, that means you're hitting the buttons or screen too hard! Stop it! You could break the screen!</b><br>5. Any credits left on the machine after the designated “Last Credit” time are forfeit.<br>‣ See front desk to determine when the “Last Credit” time for the day is.<br>6. Any player found breaking any rules may be subject to removal from the venue, their card balance forfeit and or permanently banned."

[game_1]
name = "maimai DX"
info = "Test"
double_queue = true
wait_time = 947
confirm_time = 120

[game_2]
name = "CHUNITHM"
info = ""
double_queue = false
wait_time = 785
confirm_time = 120

[game_3]
name = "ONGEKI"
info = ""
double_queue = false
wait_time = 874
confirm_time = 120

[game_4]
name = "PUMP IT UP"
info = ""
double_queue = true
wait_time = 780
confirm_time = 120
