[store]
store_name = 'GAME PARK'

[game_1]
name = 'maimai DX'
double_queue = true
wait_time = 10
confirm_time = 30

[game_2]
name = 'CHUNITHM'
double_queue = false
wait_time = 15
confirm_time = 30

[game_3]
name = 'ONGEKI'
double_queue = false
wait_time = 10
confirm_time = 10
