[store]
store_name = 'Ikigai Arcade'
store_announcement = ''

[game_1]
name = 'maimai DX'
double_queue = true
#wait_time = 947
wait_time = 5
confirm_time = 5
#confirm_time = 120

[game_2]
name = 'CHUNITHM'
double_queue = false
wait_time = 785
confirm_time = 120

[game_3]
name = 'ONGEKI'
double_queue = false
wait_time = 874
confirm_time = 120

[game_4]
name = 'PUMP IT UP'
double_queue = true
wait_time = 780
confirm_time = 120
