[store]
name = "GAME PARK"
info = ""

[game_1]
name = "maimai DX"
info = ""
double_queue = true
wait_time = 10
confirm_time = 30

[game_2]
name = "CHUNITHM"
info = ""
double_queue = false
wait_time = 15
confirm_time = 30

[game_3]
name = "ONGEKI"
info = ""
double_queue = false
wait_time = 10
confirm_time = 10

[game_4]
name = "PUMP IT UP"
info = ""
double_queue = true
wait_time = 780
confirm_time = 120
